export interface BuletinEcoDto {
  id: number;
  nr: number;
  nume: string;
  prenume: string;
  virsta: number;
  cnp: string;
  seriaCs?: string;
  domiciliu?: string;
  telefon?: string;
  diagnostic?: string;
  ficat?: string;
  colecist?: string;
  vp?: number;
  vs?: number;
  cbp?: number;
  pancreas?: string;
  splina?: string;
  rd?: string;
  rs?: string;
  vu?: string;
  prostata?: string;
  ogi?: string;
  obs?: string;
  data?: string;
  ora?: string;
  medicId?: number | null;
  medic: string;
  ceus?: string;
  hasFig1: boolean;
  hasFig2: boolean;
  hasFig3: boolean;
  hasFilm1: boolean;
  [key: string]: unknown;
}
