export interface BuletinEdiDto {
  id: number;
  nr?: number;
  nume?: string;
  prenume?: string;
  virsta?: number;
  cnp?: string;
  domiciliu?: string;
  diagnostic?: string;
  sistem: string;
  sedareT?: string;
  medicatie?: string;
  ileon?: string;
  cec?: string;
  ascendent?: string;
  transvers?: string;
  descendent?: string;
  sigmoid?: string;
  rect?: string;
  jar?: string;
  biopsiiL?: string;
  biopsiiN?: number;
  nrap?: number;
  biopsiiR?: string;
  tratament?: string;
  data?: string;
  ora?: string;
  medicId?: number | null;
  medic?: string;
  biopsiiL1?: string;
  biopsiiN1?: number;
  nrap1?: number;
  biopsiiR1?: string;
  data1?: string;
  ora1?: string;
  sedareT1?: string;
  dozaS?: number;
  medicatie1?: string;
  dozaM?: number;
  hasFig1: boolean;
  hasFig2: boolean;
  hasFig3: boolean;
  hasFilm1: boolean;
  consumabile?: string;
  materiale?: string;
  [key: string]: unknown;
}
