// <auto-generated />
using System;
using LightNap.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightNap.DataProviders.MySql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LightNap.Core.Data.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("MedicName")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.BuletinEco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("Cbp")
                        .HasColumnType("int")
                        .HasColumnName("CBP");

                    b.Property<string>("Ceus")
                        .HasColumnType("longtext")
                        .HasColumnName("CEUS");

                    b.Property<string>("Cnp")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("CNP");

                    b.Property<string>("Colecist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("PERETI NORMALI, FARA CALCULI")
                        .HasColumnName("colecist");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("longtext")
                        .HasColumnName("diagnostic");

                    b.Property<string>("Domiciliu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)")
                        .HasDefaultValue("CRAIOVA, DOLJ")
                        .HasColumnName("domiciliu");

                    b.Property<string>("Ficat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("DIAMETRU ANTEROPOSTERIOR LOB STING 0 cm, PRERENAL LOB DREPT 0 cm, ECOSTRUCTURA OMOGENA, CONTUR REGULAT, FARA PROCESE LOCALIZATE")
                        .HasColumnName("ficat");

                    b.Property<byte[]>("Fig1")
                        .HasColumnType("longblob")
                        .HasColumnName("Fig1");

                    b.Property<byte[]>("Fig2")
                        .HasColumnType("longblob")
                        .HasColumnName("Fig2");

                    b.Property<byte[]>("Fig3")
                        .HasColumnType("longblob")
                        .HasColumnName("Fig3");

                    b.Property<byte[]>("Film1")
                        .HasColumnType("longblob")
                        .HasColumnName("Film1");

                    b.Property<string>("Medic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medic");

                    b.Property<int?>("MedicId")
                        .HasColumnType("int")
                        .HasColumnName("MedicId");

                    b.Property<int>("Nr")
                        .HasColumnType("int")
                        .HasColumnName("nr");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nume");

                    b.Property<string>("Obs")
                        .HasColumnType("longtext")
                        .HasColumnName("obs");

                    b.Property<string>("Ogi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMALE")
                        .HasColumnName("ogi");

                    b.Property<DateTime?>("Ora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ora");

                    b.Property<string>("Pancreas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("OMOGEN, DIMENSIUNI NORMALE")
                        .HasColumnName("pancreas");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prenume");

                    b.Property<string>("Prostata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMALA")
                        .HasColumnName("prostata");

                    b.Property<string>("Rd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("0 cm AX LUNG, IP 0 cm, FARA CALCULI, FARA DILATATII")
                        .HasColumnName("rd");

                    b.Property<string>("Rs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("0 cm AX LUNG, IP 0 cm, FARA CALCULI, FARA DILATATII")
                        .HasColumnName("rs");

                    b.Property<string>("SeriaCs")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("seriaCS");

                    b.Property<string>("Splina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("0 cm AX LUNG")
                        .HasColumnName("splina");

                    b.Property<byte[]>("SsmaTimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("longblob")
                        .HasColumnName("SSMA_TimeStamp");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefon");

                    b.Property<int>("Virsta")
                        .HasColumnType("int")
                        .HasColumnName("virsta");

                    b.Property<int?>("Vp")
                        .HasColumnType("int")
                        .HasColumnName("VP");

                    b.Property<short?>("Vs")
                        .HasColumnType("smallint")
                        .HasColumnName("VS");

                    b.Property<string>("Vu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("GOLITA")
                        .HasColumnName("vu");

                    b.HasKey("Id");

                    b.HasIndex("MedicId");

                    b.ToTable("Buletine_ECO", (string)null);
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.BuletinEdi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Ascendent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Ascendent");

                    b.Property<string>("BiopsiiL")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("biopsii_l");

                    b.Property<string>("BiopsiiL1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("biopsii_l1");

                    b.Property<short?>("BiopsiiN")
                        .HasColumnType("smallint")
                        .HasColumnName("biopsii_n");

                    b.Property<short?>("BiopsiiN1")
                        .HasColumnType("smallint")
                        .HasColumnName("biopsii_n1");

                    b.Property<string>("BiopsiiR")
                        .HasColumnType("longtext")
                        .HasColumnName("biopsii_r");

                    b.Property<string>("BiopsiiR1")
                        .HasColumnType("longtext")
                        .HasColumnName("biopsii_r1");

                    b.Property<string>("Cec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Cec");

                    b.Property<string>("Cnp")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("CNP");

                    b.Property<string>("Consumabile")
                        .HasColumnType("longtext")
                        .HasColumnName("Consumabile");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<DateTime?>("Data1")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data1");

                    b.Property<string>("Descendent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Descendent");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("longtext")
                        .HasColumnName("diagnostic");

                    b.Property<string>("Domiciliu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)")
                        .HasDefaultValue("CRAIOVA, DOLJ")
                        .HasColumnName("domiciliu");

                    b.Property<int?>("DozaM")
                        .HasColumnType("int")
                        .HasColumnName("doza_m");

                    b.Property<int?>("DozaS")
                        .HasColumnType("int")
                        .HasColumnName("doza_s");

                    b.Property<byte[]>("Fig1")
                        .HasColumnType("longblob")
                        .HasColumnName("Fig1");

                    b.Property<byte[]>("Fig2")
                        .HasColumnType("longblob")
                        .HasColumnName("Fig2");

                    b.Property<byte[]>("Fig3")
                        .HasColumnType("longblob")
                        .HasColumnName("Fig3");

                    b.Property<byte[]>("Film1")
                        .HasColumnType("longblob")
                        .HasColumnName("Film1");

                    b.Property<string>("Ileon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Ileon");

                    b.Property<string>("Jar")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("JAR");

                    b.Property<string>("Materiale")
                        .HasColumnType("longtext")
                        .HasColumnName("Materiale");

                    b.Property<string>("Medic")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medic");

                    b.Property<int?>("MedicId")
                        .HasColumnType("int")
                        .HasColumnName("MedicId");

                    b.Property<string>("Medicatie")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medicatie");

                    b.Property<string>("Medicatie1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("medicatie1");

                    b.Property<int?>("Nr")
                        .HasColumnType("int")
                        .HasColumnName("nr");

                    b.Property<int?>("Nrap")
                        .HasColumnType("int")
                        .HasColumnName("nrap");

                    b.Property<int?>("Nrap1")
                        .HasColumnType("int")
                        .HasColumnName("nrap1");

                    b.Property<string>("Nume")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nume");

                    b.Property<DateTime?>("Ora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ora");

                    b.Property<DateTime?>("Ora1")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ora1");

                    b.Property<string>("Prenume")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prenume");

                    b.Property<string>("Rect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Rect");

                    b.Property<string>("SedareT")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sedare_t");

                    b.Property<string>("SedareT1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sedare_t1");

                    b.Property<string>("Sigmoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Sigmoid");

                    b.Property<string>("Sistem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("OLYMPUS EXERA")
                        .HasColumnName("Sistem");

                    b.Property<int?>("SistemNumarsistem")
                        .HasColumnType("int");

                    b.Property<byte[]>("SsmaTimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("longblob")
                        .HasColumnName("SSMA_TimeStamp");

                    b.Property<string>("Transvers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Transvers");

                    b.Property<string>("Tratament")
                        .HasColumnType("longtext")
                        .HasColumnName("Tratament");

                    b.Property<byte?>("Virsta")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("virsta");

                    b.HasKey("Id");

                    b.HasIndex("MedicId");

                    b.HasIndex("SistemNumarsistem");

                    b.ToTable("Buletine_EDI", (string)null);
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.BuletinEds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("BiopsiiL")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("biopsii_l");

                    b.Property<short?>("BiopsiiN")
                        .HasColumnType("smallint")
                        .HasColumnName("biopsii_n");

                    b.Property<string>("BiopsiiR")
                        .HasColumnType("longtext")
                        .HasColumnName("biopsii_r");

                    b.Property<string>("Bulb")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Bulb");

                    b.Property<string>("Cnp")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("CNP");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("longtext")
                        .HasColumnName("diagnostic");

                    b.Property<string>("Domiciliu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)")
                        .HasDefaultValue("CRAIOVA, DOLJ")
                        .HasColumnName("domiciliu");

                    b.Property<string>("Duoden")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Duoden");

                    b.Property<string>("Esofag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Esofag");

                    b.Property<string>("Jonctiune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Jonctiune");

                    b.Property<string>("Medic")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medic");

                    b.Property<int?>("MedicId")
                        .HasColumnType("int")
                        .HasColumnName("MedicId");

                    b.Property<string>("Medicatie")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("medicatie");

                    b.Property<int?>("Nr")
                        .HasColumnType("int")
                        .HasColumnName("nr");

                    b.Property<int?>("Nrap")
                        .HasColumnType("int")
                        .HasColumnName("nrap");

                    b.Property<string>("Nume")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nume");

                    b.Property<DateTime?>("Ora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ora");

                    b.Property<string>("Pilor")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Pilor");

                    b.Property<string>("Prenume")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prenume");

                    b.Property<string>("SedareT")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sedare_t");

                    b.Property<string>("Sistem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("OLYMPUS EXERA")
                        .HasColumnName("Sistem");

                    b.Property<int?>("SistemNumarsistem")
                        .HasColumnType("int");

                    b.Property<byte[]>("SsmaTimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("longblob")
                        .HasColumnName("SSMA_TimeStamp");

                    b.Property<string>("Stomac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("Stomac");

                    b.Property<string>("Tratament")
                        .HasColumnType("longtext")
                        .HasColumnName("Tratament");

                    b.Property<byte?>("Virsta")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("virsta");

                    b.HasKey("Id");

                    b.HasIndex("MedicId");

                    b.HasIndex("SistemNumarsistem");

                    b.ToTable("Buletine_EDS", (string)null);
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.Medic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MedicName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Medic");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Medici", (string)null);
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.Sistem", b =>
                {
                    b.Property<int>("Numarsistem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Sistem1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Sistem");

                    b.HasKey("Numarsistem");

                    b.ToTable("Sistem", (string)null);
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.StaticContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EditorRoles")
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastModifiedByUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReadAccess")
                        .HasColumnType("int");

                    b.Property<string>("ReaderRoles")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusChangedByUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("StatusChangedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("LastModifiedByUserId");

                    b.HasIndex("StatusChangedByUserId");

                    b.ToTable("StaticContents");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.StaticContentLanguage", b =>
                {
                    b.Property<int>("StaticContentId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedUserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("StaticContentId", "LanguageCode");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("LastModifiedUserId");

                    b.ToTable("StaticContentLanguages");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.UserSetting", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "Key");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.BuletinEco", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.Medic", null)
                        .WithMany("BuletineEco")
                        .HasForeignKey("MedicId");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.BuletinEdi", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.Medic", null)
                        .WithMany("BuletineEdi")
                        .HasForeignKey("MedicId");

                    b.HasOne("LightNap.Core.Data.Entities.Sistem", null)
                        .WithMany("BuletineEdi")
                        .HasForeignKey("SistemNumarsistem");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.BuletinEds", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.Medic", null)
                        .WithMany("BuletineEds")
                        .HasForeignKey("MedicId");

                    b.HasOne("LightNap.Core.Data.Entities.Sistem", null)
                        .WithMany("BuletineEds")
                        .HasForeignKey("SistemNumarsistem");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.Medic", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", "User")
                        .WithOne("Medic")
                        .HasForeignKey("LightNap.Core.Data.Entities.Medic", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.Notification", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.StaticContent", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedByUserId");

                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", "StatusChangedByUser")
                        .WithMany()
                        .HasForeignKey("StatusChangedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastModifiedByUser");

                    b.Navigation("StatusChangedByUser");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.StaticContentLanguage", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", "LastModifiedUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedUserId");

                    b.HasOne("LightNap.Core.Data.Entities.StaticContent", "StaticContent")
                        .WithMany("Languages")
                        .HasForeignKey("StaticContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastModifiedUser");

                    b.Navigation("StaticContent");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.UserSetting", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", "User")
                        .WithMany("UserSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LightNap.Core.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Medic");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.Medic", b =>
                {
                    b.Navigation("BuletineEco");

                    b.Navigation("BuletineEdi");

                    b.Navigation("BuletineEds");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.Sistem", b =>
                {
                    b.Navigation("BuletineEdi");

                    b.Navigation("BuletineEds");
                });

            modelBuilder.Entity("LightNap.Core.Data.Entities.StaticContent", b =>
                {
                    b.Navigation("Languages");
                });
#pragma warning restore 612, 618
        }
    }
}
